# file: switch_vlan_create_modify.yml
- hosts: switch1
  tasks:
  - name: gather facts from switch
    local_action:
      module: pro_vision_facts
      host: "{{ switch_host }}"
      username: "{{ switch_user }}"
      password: "{{ switch_password }}"

# should delete VLAN_44
  - name: should delete VLAN_44
    local_action:
      module: pro_vision_vlan
      host: "{{ switch_host }}"
      username: "{{ switch_user }}"
      password: "{{ switch_password }}"
      state: absent 
      vlan_id: 44
      vlan_name: VLAN_44

# should state VLAN_44 doesn't exist
  - name: doesn't exist delete VLAN_44
    local_action:
      module: pro_vision_vlan
      host: "{{ switch_host }}"
      username: "{{ switch_user }}"
      password: "{{ switch_password }}"
      state: absent 
      vlan_id: 44
      vlan_name: VLAN_44

# should re-create VLAN_44 
  - name: re-create VLAN_44
    local_action:
      module: pro_vision_vlan
      host: "{{ switch_host }}"
      username: "{{ switch_user }}"
      password: "{{ switch_password }}"
      state: present
      vlan_id: 44
      vlan_name: VLAN_44

# should indicate "already exists"
  - name: already exists create VLAN_44
    local_action:
      module: pro_vision_vlan
      host: "{{ switch_host }}"
      username: "{{ switch_user }}"
      password: "{{ switch_password }}"
      state: present
      vlan_id: 44
      vlan_name: VLAN_44

